import torch

INDEX_THRESHOLD = 50000
ABSTRACT_LENGTH_THRESHOLD = 100
ARTICLE_LENGTH_THRESHOLD = 400

USE_CUDA = torch.cuda.is_available()

HIDDEN_SIZE = 256
WORD_VEC_SIZE = 128
BATCH_SIZE = 1
EPOCH_NUMBER = 200
RESUME = False

PAD = "<PAD>"
UNK = "<UNK>"
SOS = "<SOS>"
EOS = "<EOS>"

PAD_TOKEN = 0
UNK_TOKEN = 1
SOS_TOKEN = 2
EOS_TOKEN = 3

GRADIENT_CLIP = 2
LEARNING_RATE = 1
DROP_OUT = 0.3
